### ISSUE TITLE
unable to view slides after cloning

### ISSUE THREAD

**Issue by melvinzhang** [melvinzhang/malmopy#15]
need to use git-lfs to get content and then unzip

**Comment by hschilling** [comment]
thanks for the fix and for sending me the zipped up version of this!

**Comment by melvinzhang** [comment]
@hschilling you're welcome :) My FOSSASIA 2019 slides are now available at https://melvinzhang.keybase.pub/fossasia2019/

**Comment by hschilling** [comment]
Perfect! Thanks
