### ISSUE TITLE
setting up Project Malmo and malmopy on Windows

### ISSUE THREAD

**Issue by melvinzhang** [melvinzhang/malmopy#16]

**Comment by dhsgisc** [comment]
needs to install Pillow first, maybe remove it from the lib

install Redhat JDK MSI file

install Python 3,.6 and check add to PATH

then unzip Proejct Malmo and double click launchClient.bat

pip install Pillow

and copy the MalmoPython.lib MalmoPython.pyd into the src folder of malmopy

test by running `python src/cliff_walking.py`

**Comment by melvinzhang** [comment]
Initial version of wiki page created at https://github.com/melvinzhang/malmopy/wiki/Running-on-Windows
