### ISSUE TITLE
install Malmo on laptops and test that sample python code works

### ISSUE THREAD

**Issue by melvinzhang** [melvinzhang/malmopy#5]
see https://github.com/melvinzhang/ai-python-course/wiki/Running-on-Mac for the how to

**Comment by melvinzhang** [comment]
@julbee did you manage to try out the installation? I'm concerned that the native library will not work properly.

**Comment by melvinzhang** [comment]
Another change is a separate folder for python code, previously it was all from the malmo zip file. Now, the malmo folder is only used to start Minecraft + Malmo plugin. The python code will be run from a different folder with only the files used for the course.

**Comment by julbee** [comment]
My oversight. One error so far on installation: 

`Traceback (most recent call last):
  File "src/cliff_walking.py", line 1, in <module>
    import malmopy
  File "/Users/juliana/Desktop/ai-python-course-master/src/malmopy.py", line 12, in <module>
    import MalmoPython
ImportError: dlopen(/Users/juliana/Desktop/ai-python-course-master/src/MalmoPython.so, 2): Library not loaded: /usr/local/opt/xerces-c/lib/libxerces-c-3.1.dylib
  Referenced from: /Users/juliana/Desktop/ai-python-course-master/src/MalmoPython.so
  Reason: image not found`

Instead of libxerces-c-3.1.dylib, I have libxerces-c-3.2.dylib.

**Comment by julbee** [comment]
On xerces-c: installed and switched version. This handles the xerces-c ImportError. Now this error:

> Traceback (most recent call last):
>   File "src/cliff_walking.py", line 1, in <module>
>     import malmopy
>   File "/Users/juliana/Desktop/ai-python-course-master/src/malmopy.py", line 12, in <module>
>     import MalmoPython
> ImportError: dynamic module does not define module export function (PyInit_MalmoPython)

**Comment by melvinzhang** [comment]
Thanks for checking. I've seen this before, it looks like their native lib does not support python3.  Can you try with python2?

**Comment by melvinzhang** [comment]
Alternatively, can you try with 0.31 package https://github.com/Microsoft/malmo/releases/download/0.31.0/Malmo-0.31.0-Linux-Centos7-64bit_Python3.4.zip

malmo/issues/623 suggest that it works with macOS and it is built for python3.

**Comment by julbee** [comment]
With python 2:

> Julianas-MBP:ai-python-course-master juliana$ python src/cliff_walking.py 
> Fatal Python error: PyThreadState_Get: no current thread
> Abort trap: 6

**Comment by melvinzhang** [comment]
No need to set the environment, it is done in malmopy, that's why I didn't include it in installation wiki page. The bug doesn't look like it is related to the MALMO_XSD_PATH.

@julbee This doesn't look good... Can you setup https://tmate.io/ on one of the Mac and launch a session. Then PM me the login details.

**Comment by melvinzhang** [comment]
@julbee the `Fatal Python error: PyThreadState_Get: no current thread` is due to the python version not compatible with the native lib. What is the version of python2 you are using? Could you try using a more recent version?

**Comment by melvinzhang** [comment]
@julbee do you recall what was the setup earlier in the year when you got it working? Alternatively we can start from the working state and try to move from that to using the nicer malmopy.

**Comment by melvinzhang** [comment]
Working now on one Mac. Need to build MalmoPython.so from source.

Next step is to replicate the setup on another Mac, may need to install dependencies via brew.

@julbee do update https://github.com/melvinzhang/ai-python-course/wiki/Running-on-Mac with any additional steps needed.

**Comment by melvinzhang** [comment]
@julbee please setup tmate on the same Mac as yesterday, I forgot to write down the steps for compilation into the wiki.

**Comment by julbee** [comment]
Duplicated the compiled MalmoPython.so to two machines this morning. One is
giving segmentation fault. With the other, I am in the midst of installing
dependencies.
ᐧ

Educating All for the Future,

Juliana Ung
LccL Coding Academy
19 Tanglin Road #05-49/50, Singapore 247909
M: +65 96918603 <+65%209691%208603> T: +65 68172957
W: lcclcoding.com Instagram: lcclcoding
<https://www.instagram.com/lcclcoding/>
FB: facebook.com/lcclcoding

**Comment by melvinzhang** [comment]
@julbee thanks for the update, if you need help taking a look at the segmentation fault, you can setup a tmate session and PM me the connection details. Do take note of the dependencies needed so that we can add it to the wiki page.

**Comment by julbee** [comment]
Setting up using instructions from "Running on Mac" section on the wiki. Result:

> LCCLs-MacBook-Air-2:ai-python-course-master lccl$ python3 src/cliff_walking.py 
> Traceback (most recent call last):
>   File "src/cliff_walking.py", line 1, in <module>
>     import malmopy
>   File "/Users/lccl/Downloads/ai-python-course-master/src/malmopy.py", line 12, in <module>
>     import MalmoPython
> ImportError: dlopen(/Users/lccl/Downloads/ai-python-course-master/src/MalmoPython.so, 2): no suitable image found.  Did find:
> 	/Users/lccl/Downloads/ai-python-course-master/src/MalmoPython.so: file too short
> 	/Users/lccl/Downloads/ai-python-course-master/lib/x86-64_macos/MalmoPython.so: file too short

**Comment by julbee** [comment]
Compiling using instructions from Wiki section: "Compiling native lib on Linux and Mac". I copied the diff file to downloaded male repo. Result:

> error: patch failed: CMakeLists.txt:38
> error: CMakeLists.txt: patch does not apply

**Comment by melvinzhang** [comment]
@julbee apologies for that, was working on bundling the so file but did not quite get it working. You still need to copy over from the first machine where we compiled it on.

**Comment by melvinzhang** [comment]
You can also dowload it from https://github.com/melvinzhang/ai-python-course/raw/master/lib/x86-64_macos/MalmoPython.so and place it in src as before.

**Comment by melvinzhang** [comment]
I've fixed https://github.com/melvinzhang/ai-python-course/wiki/Running-on-Mac to with correct instructions

**Comment by melvinzhang** [comment]
@julbee I added dependencies in step 4. Do try and let me know if it works.
